### ISSUE TITLE
Extract Provider Provisioning from README

### ISSUE THREAD

**Issue by bavellone** [ryanmcafee/flavorize#2]
The provider-specific guide in the README is pretty lengthy and not needed if using a different provider. As more providers are added, it would be easier to have README links to dedicated provisioning guides for each provider in that provider's `modules/k8s` directory alongside the terraform code.

**Comment by ryanmcafee** [comment]
That's a great idea! I'll work on streamlining the documentation over the next few days and make it more vendor netural.

**Comment by ryanmcafee** [comment]
This is now completed :)
